import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#261a00",
        "surface-variant": "#f0e1c7",
        "secondary-fixed-dim": "#ffb77a",
        "on-tertiary-fixed-variant": "#8c171b",
        "on-background": "#221b0b",
        "primary-fixed": "#ffdfa0",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "secondary": "#8f4e00",
        "primary": "#795900",
        "surface-container-high": "#f5e6cc",
        "on-secondary-fixed": "#2e1500",
        "surface-bright": "#fff8f2",
        "tertiary-container": "#ff847c",
        "tertiary-fixed-dim": "#ffb3ad",
        "error-container": "#ffdad6",
        "surface-container-highest": "#f0e1c7",
        "on-primary-fixed-variant": "#5c4300",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdcc2",
        "on-error": "#ffffff",
        "on-secondary-container": "#683700",
        "surface-tint": "#795900",
        "tertiary": "#ad302f",
        "on-surface-variant": "#4f4634",
        "on-surface": "#221b0b",
        "outline": "#817662",
        "on-tertiary-container": "#7e0a12",
        "on-primary-container": "#503a00",
        "surface-container": "#fbecd2",
        "on-secondary-fixed-variant": "#6d3a00",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#feefd5",
        "primary-container": "#d4a017",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface-dim": "#e7d8bf",
        "secondary-container": "#fe9832",
        "surface": "#fff8f2",
        "inverse-surface": "#382f1e",
        "primary-fixed-dim": "#f6be39",
        "background": "#fff8f2",
        "on-tertiary-fixed": "#410004",
        "tertiary-fixed": "#ffdad7",
        "inverse-primary": "#f6be39",
        "outline-variant": "#d3c5ae",
        "surface-container-low": "#fff2dd",
        "secondary-fixed-dim-alt": "#ffb77a",
        "primary-fixed-alt": "#ffdfa0",
        "inverse-on-surface-alt": "#feefd5",
        // ── Previously missing token (used in AdminDashboard activity icons) ──
        "secondary-fixed-alt": "#ffdcc2",
        // on-secondary-fixed already defined above — alias here for safety
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        // Fix: must be 9999px (true pill/circle), not 0.75rem
        full: "9999px",
      },
      spacing: {
        "section-padding-lg": "120px",
        gutter: "24px",
        unit: "8px",
        "margin-mobile": "16px",
        // Removed from spacing — kept only in maxWidth to avoid Tailwind resolution conflict
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        h3: ["var(--font-playfair)", "serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        h1: ["var(--font-playfair)", "serif"],
        h2: ["var(--font-playfair)", "serif"],
        "h1-mobile": ["var(--font-playfair)", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["36px", { lineHeight: "1.3", fontWeight: "600" }],
        "h1-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
